/**
 * @file    board_config.h
 * @brief   Everything that depends on the physical board: timers, pins.
 *          Must match the CubeMX (.ioc) configuration. Change HERE only.
 */
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "main.h"
#include <stdint.h>

/* Number of wheels wired on this board (M1: one wheel; M3: four). */
#define BOARD_NUM_WHEELS    (1U)

/* Handles generated by CubeMX. */
extern TIM_HandleTypeDef  htim1;   /* PWM         (TIM1_CH1 = PA8)          */
extern TIM_HandleTypeDef  htim3;   /* encoder     (TIM3 CH1/CH2 = PB4/PB5)  */
extern UART_HandleTypeDef huart2;  /* console     (PA2 TX / PA3 RX)         */

/* ---- GPIO (configure as push-pull outputs, initial level LOW, in CubeMX) */
#define BOARD_LED_PORT          (GPIOC)
#define BOARD_LED_PIN           (GPIO_PIN_13)

/* Global enable of all BTS7960 (R_EN and L_EN wired together). LOW = coast. */
#define BOARD_BRIDGE_EN_PORT    (GPIOB)
#define BOARD_BRIDGE_EN_PIN     (GPIO_PIN_14)

/* Direction gates (74HC08):  RPWM = PWM AND ENR,  LPWM = PWM AND ENL.      */
#define BOARD_W0_ENR_PORT       (GPIOB)
#define BOARD_W0_ENR_PIN        (GPIO_PIN_12)
#define BOARD_W0_ENL_PORT       (GPIOB)
#define BOARD_W0_ENL_PIN        (GPIO_PIN_13)

#endif /* BOARD_CONFIG_H */
